eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.253:8761/eureka/


server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /farm/**
      serviceId: farm-server
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

  threadPool:
      useSeparateThreadPools: true

hystrix :
 command :
   default:
    execution:
     isolation:
      thread:
      timeoutInMilliseconds: 5000


